CONNECT SYS AS SYSDBA
-- 090322

CREATE TABLESPACE UNAM DATAFILE 'D:/Projects/BDavanzada/UNAM.DBF' SIZE 5M;

CREATE USER BLUE IDENTIFIED BY 090322 DEFAULT TABLESPACE UNAM;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, UNLIMITED TABLESPACE TO BLUE;

CONNECT BLUE
-- 090322

SELECT * FROM CAT;

CREATE TABLE AREA (
    ID_MATERIA VARCHAR(3) PRIMARY KEY,
    DESCRIPCION_MATERIA VARCHAR(30)
);

CREATE TABLE CURSO (
    NUM_CURSO VARCHAR(10) PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(30),
    CREDITOS VARCHAR(2)
);

CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE VARCHAR(4) PRIMARY KEY,
    APELLIDO VARCHAR(15),
    NOMBRE VARCHAR(15),
    INICIAL CHAR(1),
    ID_MATERIA VARCHAR(3),
    CONSTRAINT A_AREA 
    FOREIGN KEY (ID_MATERIA) REFERENCES AREA(ID_MATERIA)
);

CREATE TABLE INSCRIPCION (
    ID_ESTUDIANTE VARCHAR(4),
    NUM_CURSO VARCHAR(10),
    FECHA_FIN DATE,
    PRIMARY KEY (ID_ESTUDIANTE, NUM_CURSO),
    CONSTRAINT A_CURSO
    FOREIGN KEY (NUM_CURSO) REFERENCES CURSO(NUM_CURSO),
    CONSTRAINT A_ESTUDIANTE
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
);

insert all 
    INTO AREA VALUES ('MAT', 'Matematicas')
    INTO AREA VALUES ('FIl', 'Filosofia')
    INTO AREA VALUES ('ING', 'Literatura inglesa')
    INTO AREA VALUES ('MUS', 'Musica')
    INTO AREA VALUES ('CC', 'Ciencias de la computacion')
    INTO CURSO VALUES ('MAT0011', 'Matematicas discretas', '12')
    INTO CURSO VALUES ('MAT0027', 'Calculo I', '12')
    INTO CURSO VALUES ('ING0010', 'Ingles Clasico', '8')
    INTO CURSO VALUES ('FIL0010', 'Introduccion a la filosofia', '8')
    INTO CURSO VALUES ('CC00010', 'Lenguajes de programacion', '10')
    INTO CURSO VALUES ('SOC0102', 'Ascenso del hombre', '8')
    INTO CURSO VALUES ('MUS0002', 'Origen del Jazz', '8')
    INTO CURSO VALUES ('ING0101', 'Shakespeare II', '8')
    INTO ESTUDIANTE VALUES ('2907', 'Lopez', 'Jacobo', 'R', 'MAT')
    INTO ESTUDIANTE VALUES ('4019', 'Perez', 'Jenny', 'L', 'FIl')
    INTO ESTUDIANTE VALUES ('5145', 'Santana', 'Luis', 'M', 'ING')
    INTO ESTUDIANTE VALUES ('6132', 'Morrison', 'Javier', 'Q', 'MUS')
    INTO ESTUDIANTE VALUES ('7810', 'Martinez', 'Ricardo', 'E', 'CC')
    INTO ESTUDIANTE VALUES ('8966', 'Juarez', 'Samantha', 'L', 'ING')
    INTO INSCRIPCION VALUES ('2907', 'MAT0011', '01/08/15')
    INTO INSCRIPCION VALUES ('2907', 'MAT0027', '30/04/15')
    INTO INSCRIPCION VALUES ('2907', 'ING0010', '30/12/15')
    INTO INSCRIPCION VALUES ('4019', 'FIL0010', '30/04/15')
    INTO INSCRIPCION VALUES ('4019', 'CC00010', '30/04/15')
    INTO INSCRIPCION VALUES ('5145', 'SOC0102', '01/08/15')
    INTO INSCRIPCION VALUES ('6132', 'MUS0002', '30/04/15')
    INTO INSCRIPCION VALUES ('6132', 'SOC0102', '01/08/15')
    INTO INSCRIPCION VALUES ('8966', 'ING0010', '30/04/15')
    INTO INSCRIPCION VALUES ('8966', 'ING0101', '01/08/15')
    SELECT * FROM dual;

SELECT * FROM AREA;
SELECT * FROM CURSO;
SELECT * FROM ESTUDIANTE;
SELECT * FROM INSCRIPCION;

CREATE OR REPLACE PROCEDURE CONSULTA (
    V_CODIGO IN ESTUDIANTE.ID_ESTUDIANTE%TYPE,
    V_APELLIDO OUT ESTUDIANTE.APELLIDO%TYPE,
    V_NOMBRE OUT ESTUDIANTE.NOMBRE%TYPE,
    V_AREA_MATERIA OUT AREA.ID_MATERIA%TYPE
)
IS 
BEGIN
    SELECT APELLIDO, NOMBRE, ID_MATERIA
    INTO V_APELLIDO, V_NOMBRE, V_AREA_MATERIA
    FROM ESTUDIANTE
    WHERE ID_ESTUDIANTE = V_CODIGO;
END CONSULTA;
/

VARIABLE G_APELLIDO VARCHAR2(15);
VARIABLE G_NOMBRE VARCHAR2(15);
VARIABLE G_AREA_MATERIA VARCHAR2(3);

EXECUTE CONSULTA ('2907', :G_APELLIDO, :G_NOMBRE, :G_AREA_MATERIA);

PRINT G_APELLIDO;
PRINT G_NOMBRE;
PRINT G_AREA_MATERIA;



CREATE OR REPLACE PROCEDURE formato_tel (
    v_Telefono IN OUT VARCHAR2
)
    IS
    BEGIN
        v_Telefono := '(' || SUBSTR(v_Telefono, 1, 3) || ') ' || SUBSTR(v_Telefono, 4, 3) || '-' || SUBSTR(v_Telefono, 7, 4);
    END formato_tel;
/

VARIABLE g_telefono VARCHAR2(15);

BEGIN 
    :g_telefono := '8006330575';
END;
/

EXECUTE formato_tel(:g_telefono);

PRINT g_telefono;



SELECT 
    ESTUDIANTE.NOMBRE,
    ESTUDIANTE.APELLIDO,
    AREA.DESCRIPCION_MATERIA,
    CURSO.NOMBRE_CURSO,
    INSCRIPCION.FECHA_FIN
FROM ESTUDIANTE
JOIN AREA ON ESTUDIANTE.ID_MATERIA = AREA.ID_MATERIA
JOIN INSCRIPCION  ON ESTUDIANTE.ID_ESTUDIANTE = INSCRIPCION.ID_ESTUDIANTE
JOIN CURSO ON INSCRIPCION.NUM_CURSO = CURSO.NUM_CURSO;



CREATE OR REPLACE 