CREATE OR REPLACE PROCEDURE EJEMPLO 
(ID_ IN CHOFER.rfc%TYPE) IS NOMBRE VARCHAR(20);
BEGIN
    SELECT nombre_chofer INTO NOMBRE FROM CHOFER WHERE rfc = ID_;
    DBMS_OUTPUT.PUT_LINE(NOMBRE);
END;
/

SET SERVEROUTPUT ON;


EXECUTE EJEMPLO('CHOFR002BBB');




-- procedimiento que presente el resultado de la suma de dos numeros
CREATE OR REPLACE PROCEDURE SUMA_NUMEROS
(NUM1 IN NUMBER, NUM2 IN NUMBER) IS
RESULTADO NUMBER;
BEGIN
    RESULTADO := NUM1 + NUM2;
    DBMS_OUTPUT.PUT_LINE('La suma es: ' || RESULTADO);
END;
/

EXECUTE SUMA_NUMEROS(5, 10);


CREATE TABLE ESTUDIANTE ( 
    ID_ESTUDIANTE VARCHAR2(4) PRIMARY KEY,
    APELLIDO VARCHAR2(15),
    NOMBRE VARCHAR2(15),
    ID_MATERIA VARCHAR2(3)
    );

INSERT INTO ESTUDIANTE VALUES ('2907', 'PEREZ', 'JUAN', 'MAT');

CREATE OR REPLACE PROCEDURE CONSULTA (
    V_CODIGO IN ESTUDIANTE.ID_ESTUDIANTE%TYPE,
    V_APELLIDO OUT ESTUDIANTE.APELLIDO%TYPE,
    V_NOMBRE OUT ESTUDIANTE.NOMBRE%TYPE,
    V_MATERIA OUT ESTUDIANTE.ID_MATERIA%TYPE
) IS
BEGIN
    SELECT APELLIDO, NOMBRE, ID_MATERIA 
    INTO V_APELLIDO, V_NOMBRE, V_MATERIA
    FROM ESTUDIANTE
    WHERE ID_ESTUDIANTE = V_CODIGO;
END;
/

VARIABLE APELLIDO VARCHAR2(15);
VARIABLE NOMBRE VARCHAR2(15);
VARIABLE MATERIA VARCHAR2(3);

EXECUTE CONSULTA('2907', :APELLIDO, :NOMBRE, :MATERIA);
PRINT APELLIDO;
PRINT NOMBRE;
PRINT MATERIA;


CREATE TABLE CLIENTES (
    CODIGO VARCHAR2(2),
    NOMBRE VARCHAR2(15),
    LIMITE NUMBER(8,2)
    );

CREATE OR REPLACE TRIGGER INSERCION
AFTER INSERT ON CLIENTES 
FOR EACH ROW 
BEGIN
    DBMS_OUTPUT.PUT_LINE('CLIENTE ADICIONADO' || :NEW.NOMBRE || :NEW.LIMITE);
END;
/

set serveroutput on;

INSERT INTO CLIENTES VALUES ('01', 'JUAN PEREZ', 5000);
INSERT INTO CLIENTES VALUES ('02', 'MARIO LOPEZ', 7000);
INSERT INTO CLIENTES VALUES ('03', 'LUIS GOMEZ', 6000);
INSERT INTO CLIENTES VALUES ('04', 'ANA MARTINEZ', 8000);
INSERT INTO CLIENTES VALUES ('05', 'SARA DIAZ', 9000);


CREATE TABLE AUDITOR (
    CAMBIO VARCHAR2(40)
);

DROP TABLE AUDITOR PURGE;

CREATE OR REPLACE TRIGGER AUDITAR_CLIENTES
AFTER UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITOR VALUES ('ANTERIOR:' || :OLD.LIMITE || ' NUEVO:' || :NEW.LIMITE);
END;
/

UPDATE CLIENTES SET LIMITE = 10000 WHERE CODIGO = '03';
UPDATE CLIENTES SET LIMITE = 12000 WHERE CODIGO = '05';
UPDATE CLIENTES SET LIMITE = 15000 WHERE CODIGO = '01';

SELECT * FROM AUDITOR;

CREATE TABLE ESTADOS (
    ID_ESTADO VARCHAR2(3) PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(20)
);

INSERT INTO ESTADOS VALUES ('MEX', 'MEXICO');
INSERT INTO ESTADOS VALUES ('JAL', 'JALISCO');
INSERT INTO ESTADOS VALUES ('NLE', 'NUEVO LEON');
INSERT INTO ESTADOS VALUES ('PUE', 'PUEBLA');
INSERT INTO ESTADOS VALUES ('GUA', 'GUANAJUATO');



ALTER TABLE CLIENTES ADD ESTADO VARCHAR2(3);

UPDATE CLIENTES SET ESTADO = 'MEX' WHERE CODIGO IN ('01', '02');
UPDATE CLIENTES SET ESTADO = 'JAL' WHERE CODIGO = '03';
UPDATE CLIENTES SET ESTADO = 'NLE' WHERE CODIGO = '04';
UPDATE CLIENTES SET ESTADO = 'PUE' WHERE CODIGO = '05';

SELECT * FROM CLIENTES;


CREATE OR REPLACE VIEW CLIENTES_ESTADOS AS
SELECT NOMBRE, LIMITE, NOMBRE_ESTADO
FROM CLIENTES, ESTADOS
WHERE CLIENTES.ESTADO = ESTADOS.ID_ESTADO;

SELECT * FROM CLIENTES_ESTADOS;

CREATE OR REPLACE TRIGGER SUSTITUCION
INSTEAD OF DELETE OR INSERT 
ON CLIENTES_ESTADOS
FOR EACH ROW
BEGIN
    IF DELETING THEN 
        INSERT INTO AUDITOR VALUES ('BORRADO '|| :OLD.LIMITE);
    END IF;
    IF INSERTING THEN 
        INSERT INTO AUDITOR VALUES ('INSERTADO '|| :NEW.LIMITE);
    END IF;
END;
/

DELETE FROM CLIENTES_ESTADOS WHERE LIMITE = 12000;
INSERT INTO CLIENTES_ESTADOS (NOMBRE, LIMITE, NOMBRE_ESTADO)
VALUES ('CARLOS SANCHEZ', 11000, 'GUANAJUATO');
SELECT * FROM AUDITOR;


CREATE OR REPLACE PROCEDURE LECTURA
IS CURSOR TABLA_VIRTUAL IS 
    SELECT * FROM ESTUDIANTE;
    ARREGLO TABLA_VIRTUAL%ROWTYPE;
BEGIN
    OPEN TABLA_VIRTUAL;
    FETCH TABLA_VIRTUAL INTO ARREGLO;
    WHILE TABLA_VIRTUAL%FOUND 
    LOOP 
        DBMS_OUTPUT.PUT_LINE('NOMBRE:' || ARREGLO.NOMBRE || ' APELLIDO: ' || ARREGLO.APELLIDO);
        FETCH TABLA_VIRTUAL INTO ARREGLO;
    END LOOP;
    CLOSE TABLA_VIRTUAL;
END;
/

EXECUTE LECTURA;

CREATE OR REPLACE PROCEDURE CURSOR_FORLLOOP
IS CURSOR CR_LOOP IS
    SELECT * FROM CURSO;
    V_RECEPTOR CR_LOOP%ROWTYPE;
BEGIN
    FOR V_RECEPTOR IN CR_LOOP 
    LOOP 
        DBMS_OUTPUT.PUT_LINE(CR_LOOP%ROWCOUNT || '' || V_RECEPTOR.NOMBRE_CURSO);
    END LOOP;
END;
/

